DROP TABLE IF EXISTS SENSOR;
CREATE TABLE IF NOT EXISTS SENSOR(
    ID_SENSOR INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    LIB_SENSOR TEXT NOT NULL,
    TYP_SENSOR TEXT CHECK (TYP_SENSOR IN ('CO2', 'POW'))
);

DROP TABLE IF EXISTS DATA;
CREATE TABLE IF NOT EXISTS DATA(
    ID_DATA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    LIB_DATA TEXT NOT NULL,
    VAL_DATA REAL NOT NULL,
    DTE_DATA DATE DEFAULT (datetime('now', 'localtime')),
    ID_SENSOR INTEGER REFERENCES SENSOR(ID_SENSOR)
);

INSERT INTO SENSOR(LIB_SENSOR, TYP_SENSOR) VALUES('horloge', 'CO2');
INSERT INTO SENSOR(LIB_SENSOR, TYP_SENSOR) VALUES('Janitza 604', 'POW');
